name: Python application
on:
  push:
    branches:
      - main # 仅当推送到main分支才会运行
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v3

      - name: 安装 Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: 安装模块
        run: |
          pip install -r requirements.txt
      - name: 生成json文件
        run: |
          export TZ='Asia/Shanghai'
          python build.py
      - name: 清理Python缓存文件
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.pyc" -delete
          find . -name "*.pyo" -delete
          find . -name "*.pyd" -delete
      - name: 暂存提交
        run: |
          git config --global user.name 'xiangming'
          git config --global user.email 'zd2uiv@sina.com'
          export TZ='Asia/Shanghai'
          git add .
          git commit -m "update" -a
      - name: 推送
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
